const CARD_WIDTH_RATIO = 0.06493506493;
const ACTIVE_PANEL_WIDTH_RATIO = CARD_WIDTH_RATIO;
const ACTIVE_PANEL_BUTTON_WIDTH_RATIO = 0.05411255411;
const OPPONENT_START_X_RATIO = 0.4605885;
const OPPONENT_START_Y_RATIO = 0.1920103;
const OPPONENT_END_X_RATIO = 0.5410156;
const OPPONENT_END_Y_RATIO = 0.0476804;

export const CardConstants = {
    CARD_WIDTH_RATIO,
    CARD_HEIGHT_RATIO: CARD_WIDTH_RATIO * 1.615,
    ACTIVE_PANEL_WIDTH_RATIO,
    ACTIVE_PANEL_HEIGHT_RATIO: ACTIVE_PANEL_WIDTH_RATIO / 1.617,
    ACTIVE_PANEL_BUTTON_WIDTH_RATIO,
    ACTIVE_PANEL_BUTTON_HEIGHT_RATIO: ACTIVE_PANEL_BUTTON_WIDTH_RATIO / 1.617,
    OPPONENT_START_X_RATIO,
    OPPONENT_START_Y_RATIO,
    OPPONENT_END_X_RATIO,
    OPPONENT_END_Y_RATIO,
};