export enum ActionType {
    NONE,
    GENERAL_ATTACK_UNIT = "GENERAL_ATTACK_UNIT",
    GENERAL_ATTACK_MASTER = "GENERAL_ATTACK_MASTER",
    TARGETING_SKILL_UNIT = "TARGETING_SKILL_UNIT",
    TARGETING_SKILL_MASTER = "TARGETING_SKILL_MASTER",
}